GET http://localhost:3000/test-db

#####
### Create account
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "email": "phuc2006@example.com",
    "password_hash": "12345",
    "full_name": "Phuc 12345",
    "role": "learner",
    "status": "active"
}

### Get all accounts
GET http://localhost:3000/accounts


### Login - Test Learner
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test.learner@example.com",
  "password": "TEMP_PASSWORD_HASH"
}

### Login - Learner
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "letrongphuc@hcmut.com",
  "password": "password_phuc_123456"
}
