-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-10-01T13:01:07.109Z

CREATE TYPE "account_role" AS ENUM (
  'user',
  'learner',
  'instructor',
  'admin'
);

CREATE TABLE "accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(254) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "full_name" varchar(150) NOT NULL,
  "role" account_role NOT NULL DEFAULT 'user',
  "avatar_url" text,
  "bio" text,
  "target_overall_band" numeric(3,1),
  "target_exam_date" date,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "role_applications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applicant_id" bigint NOT NULL,
  "requested_role" varchar(20) NOT NULL,
  "application_text" text NOT NULL,
  "evidence_url" text,
  "status" varchar(20) NOT NULL,
  "reviewed_by" bigint,
  "review_note" text,
  "submitted_at" timestamptz NOT NULL,
  "reviewed_at" timestamptz
);

CREATE TABLE "auth_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token_hash" text UNIQUE NOT NULL,
  "purpose" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "consumed_at" timestamptz,
  "revoked_at" timestamptz
);

CREATE TABLE "skills" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" bigint,
  "code" varchar(80) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" text
);

CREATE TABLE "skill_prerequisites" (
  "skill_id" bigint NOT NULL,
  "prerequisite_skill_id" bigint NOT NULL,
  "minimum_mastery" numeric(5,4) NOT NULL,
  PRIMARY KEY ("skill_id", "prerequisite_skill_id")
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL,
  "slug" varchar(140) UNIQUE NOT NULL
);

CREATE TABLE "courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "instructor_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "title" varchar(250) NOT NULL,
  "slug" varchar(280) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "prerequisite_text" text,
  "thumbnail_url" text,
  "status" varchar(20) NOT NULL,
  "is_featured" boolean NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "published_at" timestamptz
);

CREATE TABLE "course_skills" (
  "course_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "initial_band" numeric(3,1) NOT NULL,
  "current_difficulty_rating" numeric(10,3) NOT NULL,
  "weight" numeric(6,5) NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("course_id", "skill_id")
);

CREATE TABLE "course_prerequisites" (
  "course_id" bigint NOT NULL,
  "prerequisite_course_id" bigint NOT NULL,
  PRIMARY KEY ("course_id", "prerequisite_course_id")
);

CREATE TABLE "chapters" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "title" varchar(250) NOT NULL,
  "position" integer NOT NULL
);

CREATE TABLE "lessons" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chapter_id" bigint NOT NULL,
  "title" varchar(250) NOT NULL,
  "position" integer NOT NULL,
  "is_required" boolean NOT NULL,
  "required_watch_percentage" numeric(5,2) NOT NULL,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "videos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint UNIQUE NOT NULL,
  "video_url" text NOT NULL,
  "duration_seconds" integer NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "lesson_materials" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "title" varchar(250) NOT NULL,
  "material_type" varchar(20) NOT NULL,
  "resource_url" text,
  "text_content" text,
  "mime_type" varchar(120),
  "duration_seconds" integer,
  "is_required" boolean NOT NULL,
  "position" integer NOT NULL
);

CREATE TABLE "lesson_skills" (
  "lesson_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "minimum_mastery" numeric(5,4) NOT NULL,
  "expected_mastery" numeric(5,4) NOT NULL,
  PRIMARY KEY ("lesson_id", "skill_id")
);

CREATE TABLE "enrollments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "learner_id" bigint NOT NULL,
  "course_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL,
  "resume_lesson_id" bigint,
  "enrolled_at" timestamptz NOT NULL,
  "last_accessed_at" timestamptz,
  "withdrawn_at" timestamptz,
  "completed_at" timestamptz
);

CREATE TABLE "lesson_progress" (
  "enrollment_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL,
  "started_at" timestamptz NOT NULL,
  "last_accessed_at" timestamptz NOT NULL,
  "completed_at" timestamptz,
  PRIMARY KEY ("enrollment_id", "lesson_id")
);

CREATE TABLE "material_progress" (
  "enrollment_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "last_position_seconds" integer,
  "completed_at" timestamptz,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("enrollment_id", "material_id")
);

CREATE TABLE "video_progress" (
  "enrollment_id" bigint NOT NULL,
  "video_id" bigint NOT NULL,
  "last_position_seconds" integer NOT NULL,
  "completed_at" timestamptz,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("enrollment_id", "video_id")
);

CREATE TABLE "video_watch_segments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" bigint NOT NULL,
  "video_id" bigint NOT NULL,
  "start_second" integer NOT NULL,
  "end_second" integer NOT NULL,
  "recorded_at" timestamptz NOT NULL
);

CREATE TABLE "assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" bigint NOT NULL,
  "course_id" bigint,
  "lesson_id" bigint,
  "assigned_learner_id" bigint,
  "title" varchar(250) NOT NULL,
  "purpose" varchar(20) NOT NULL,
  "response_mode" varchar(20) NOT NULL,
  "status" varchar(20) NOT NULL,
  "is_required" boolean NOT NULL,
  "question_count" integer,
  "time_limit_seconds" integer,
  "opens_at" timestamptz,
  "due_at" timestamptz,
  "max_attempts" integer,
  "passing_percent" numeric(5,2) NOT NULL,
  "week_start" date,
  "grading_rubric" jsonb,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "question_banks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint NOT NULL,
  "course_id" bigint,
  "name" varchar(200) NOT NULL,
  "description" text,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_bank_id" bigint NOT NULL,
  "creator_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "source_lesson_id" bigint,
  "question_type" varchar(20) NOT NULL,
  "prompt" text NOT NULL,
  "media_url" text,
  "answer_key" jsonb,
  "explanation" text,
  "difficulty_rating" numeric(10,3) NOT NULL,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "question_options" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" bigint NOT NULL,
  "option_text" text NOT NULL,
  "is_correct" boolean NOT NULL,
  "position" integer NOT NULL
);

CREATE TABLE "assessment_questions" (
  "assessment_id" bigint NOT NULL,
  "question_id" bigint NOT NULL,
  "max_points" numeric(8,2) NOT NULL,
  "is_required" boolean NOT NULL,
  PRIMARY KEY ("assessment_id", "question_id")
);

CREATE TABLE "assessment_attempts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessment_id" bigint NOT NULL,
  "learner_id" bigint NOT NULL,
  "enrollment_id" bigint,
  "attempt_number" integer NOT NULL,
  "status" varchar(25) NOT NULL,
  "started_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "submitted_at" timestamptz,
  "submission_reason" varchar(20),
  "max_points" numeric(10,2) NOT NULL,
  "score" numeric(10,2),
  "passing_percent_snapshot" numeric(5,2) NOT NULL,
  "grading_rubric_snapshot" jsonb,
  "is_passed" boolean,
  "graded_by" bigint,
  "graded_at" timestamptz,
  "feedback" text
);

CREATE TABLE "attempt_questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attempt_id" bigint NOT NULL,
  "question_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "position" integer NOT NULL,
  "question_snapshot" jsonb NOT NULL,
  "answer_key_snapshot" jsonb NOT NULL,
  "max_points" numeric(8,2) NOT NULL
);

CREATE TABLE "attempt_answers" (
  "attempt_question_id" bigint PRIMARY KEY NOT NULL,
  "answer_payload" jsonb NOT NULL,
  "awarded_points" numeric(8,2),
  "feedback" text,
  "answered_at" timestamptz NOT NULL,
  "graded_by" bigint,
  "graded_at" timestamptz
);

CREATE TABLE "submission_files" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attempt_id" bigint NOT NULL,
  "object_key" text NOT NULL,
  "original_name" varchar(255) NOT NULL,
  "mime_type" varchar(120) NOT NULL,
  "size_bytes" bigint NOT NULL,
  "uploaded_at" timestamptz NOT NULL
);

CREATE TABLE "lesson_exemptions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "basis_attempt_id" bigint NOT NULL,
  "reason" text NOT NULL,
  "algorithm_version" varchar(80) NOT NULL,
  "granted_at" timestamptz NOT NULL,
  "revoked_at" timestamptz
);

CREATE TABLE "learner_skill_states" (
  "learner_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "ability_rating" numeric(10,3) NOT NULL,
  "estimated_band" numeric(3,1),
  "mastery_score" numeric(5,4) NOT NULL,
  "target_band" numeric(3,1),
  "uncertainty" numeric(10,4),
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("learner_id", "skill_id")
);

CREATE TABLE "learner_rating_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "learner_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "source_attempt_id" bigint NOT NULL,
  "rating_before" numeric(10,3),
  "rating_after" numeric(10,3) NOT NULL,
  "band_after" numeric(3,1),
  "mastery_after" numeric(5,4) NOT NULL,
  "algorithm_version" varchar(80) NOT NULL,
  "calculation_inputs" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "course_reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" bigint UNIQUE NOT NULL,
  "star_rating" smallint NOT NULL,
  "perceived_difficulty" varchar(20) NOT NULL,
  "comment" text,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "course_rating_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "source_attempt_id" bigint,
  "source_review_id" bigint,
  "rating_before" numeric(10,3) NOT NULL,
  "rating_after" numeric(10,3) NOT NULL,
  "algorithm_version" varchar(80) NOT NULL,
  "calculation_inputs" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "recommendations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" uuid NOT NULL,
  "learner_id" bigint NOT NULL,
  "course_id" bigint NOT NULL,
  "rank" integer NOT NULL,
  "match_score" numeric(10,5) NOT NULL,
  "reason" text NOT NULL,
  "algorithm_version" varchar(80) NOT NULL,
  "input_snapshot" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "discussions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "author_id" bigint NOT NULL,
  "parent_id" bigint,
  "content" text NOT NULL,
  "is_resolved" boolean NOT NULL,
  "is_pinned" boolean NOT NULL,
  "status" varchar(20) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_id" bigint NOT NULL,
  "notification_type" varchar(40) NOT NULL,
  "course_id" bigint,
  "lesson_id" bigint,
  "assessment_id" bigint,
  "title" varchar(250) NOT NULL,
  "body" text NOT NULL,
  "dedupe_key" varchar(200) NOT NULL,
  "created_at" timestamptz NOT NULL,
  "read_at" timestamptz
);

CREATE TABLE "content_reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_id" bigint NOT NULL,
  "course_id" bigint,
  "lesson_id" bigint,
  "discussion_id" bigint,
  "review_id" bigint,
  "reason" text NOT NULL,
  "status" varchar(20) NOT NULL,
  "reviewed_by" bigint,
  "resolution_note" text,
  "created_at" timestamptz NOT NULL,
  "resolved_at" timestamptz
);

CREATE TABLE "audit_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" bigint,
  "actor_role_snapshot" varchar(20),
  "action" varchar(80) NOT NULL,
  "entity_type" varchar(80) NOT NULL,
  "entity_id" varchar(80) NOT NULL,
  "before_data" jsonb,
  "after_data" jsonb,
  "reason" text,
  "created_at" timestamptz NOT NULL
);

CREATE UNIQUE INDEX ON "chapters" ("course_id", "position");

CREATE UNIQUE INDEX ON "lessons" ("chapter_id", "position");

CREATE UNIQUE INDEX ON "lesson_materials" ("lesson_id", "position");

CREATE UNIQUE INDEX ON "enrollments" ("learner_id", "course_id");

CREATE UNIQUE INDEX ON "question_options" ("question_id", "position");

CREATE UNIQUE INDEX ON "assessment_attempts" ("assessment_id", "learner_id", "attempt_number");

CREATE UNIQUE INDEX ON "attempt_questions" ("attempt_id", "position");

CREATE UNIQUE INDEX ON "attempt_questions" ("attempt_id", "question_id");

CREATE UNIQUE INDEX ON "learner_rating_events" ("source_attempt_id", "skill_id");

CREATE UNIQUE INDEX ON "recommendations" ("batch_id", "course_id");

CREATE UNIQUE INDEX ON "recommendations" ("batch_id", "rank");

CREATE UNIQUE INDEX ON "notifications" ("recipient_id", "dedupe_key");

COMMENT ON TABLE "accounts" IS 'Tài khoản mới có role=user. Sau duyệt, đổi thành learner hoặc instructor; luôn đúng một role. Đăng nhập không đặt lại role. Giữ lịch sử học cũ khi chuyển role; quyền thao tác mới theo role hiện tại.';

COMMENT ON COLUMN "accounts"."email" IS 'Chuẩn hóa lowercase trước khi lưu';

COMMENT ON COLUMN "accounts"."password_hash" IS 'Không lưu mật khẩu thô';

COMMENT ON COLUMN "accounts"."role" IS 'Một role duy nhất: user / learner / instructor / admin. Role được thay thế khi duyệt, không thêm role thứ hai.';

COMMENT ON COLUMN "accounts"."target_overall_band" IS 'Mục tiêu IELTS tổng, 4.0..9.0 bước 0.5';

COMMENT ON COLUMN "accounts"."target_exam_date" IS 'Ngày thi mục tiêu nếu có';

COMMENT ON COLUMN "accounts"."status" IS 'active / suspended / deleted';

COMMENT ON TABLE "role_applications" IS 'Hồ sơ xin quyền dùng chung; requested_role=instructor chính là instructor application. Giữ quy tắc tài khoản mới là user và learner/instructor được duyệt sau. Một pending application mỗi applicant; chỉ admin duyệt; từ chối cần lý do. Approve kiểm tra role hiện tại và đổi accounts.role sang requested_role, cập nhật hồ sơ, notification và audit trong cùng transaction. Reject giữ nguyên role. Không tự cấp admin từ form này.';

COMMENT ON COLUMN "role_applications"."requested_role" IS 'learner / instructor; không cho xin admin';

COMMENT ON COLUMN "role_applications"."application_text" IS 'Lý do và trình độ/kinh nghiệm khi xin instructor';

COMMENT ON COLUMN "role_applications"."evidence_url" IS 'Minh chứng cho hồ sơ instructor nếu tiêu chí yêu cầu';

COMMENT ON COLUMN "role_applications"."status" IS 'pending / approved / rejected';

COMMENT ON TABLE "auth_tokens" IS 'Phiên đăng nhập và token khôi phục mật khẩu có thể thu hồi.';

COMMENT ON COLUMN "auth_tokens"."token_hash" IS 'Chỉ lưu hash của refresh/reset token';

COMMENT ON COLUMN "auth_tokens"."purpose" IS 'refresh / password_reset';

COMMENT ON COLUMN "auth_tokens"."consumed_at" IS 'Dùng một lần với password_reset';

COMMENT ON TABLE "skills" IS 'Bốn kỹ năng IELTS và các kỹ năng thành phần. Cây parent_id phải không có chu trình. Seed bốn kỹ năng gốc; kỹ năng con là đề xuất bổ sung cho Direction 3.';

COMMENT ON COLUMN "skills"."parent_id" IS 'NULL với Listening, Reading, Writing, Speaking';

COMMENT ON COLUMN "skills"."code" IS 'reading / reading.inference ...';

COMMENT ON TABLE "skill_prerequisites" IS 'Kiến thức tiên quyết để xây mastery map có quan hệ phụ thuộc. Hai skill khác nhau; đồ thị prerequisite không có chu trình.';

COMMENT ON COLUMN "skill_prerequisites"."minimum_mastery" IS '0..1';

COMMENT ON TABLE "categories" IS 'Danh mục do admin quản lý.';

COMMENT ON TABLE "courses" IS 'Khóa học do một giảng viên sở hữu. instructor_id phải có quyền instructor; API kiểm tra chủ sở hữu. Archive/ẩn khi đã có người học; không xóa dây chuyền lịch sử.';

COMMENT ON COLUMN "courses"."prerequisite_text" IS 'Điều kiện đầu vào mô tả bằng văn bản';

COMMENT ON COLUMN "courses"."status" IS 'draft / published / hidden / archived';

COMMENT ON COLUMN "courses"."is_featured" IS 'Admin chọn hiển thị nổi bật';

COMMENT ON TABLE "course_skills" IS 'Mức độ khó riêng theo từng kỹ năng của khóa học. Tổng weight của một course bằng 1; không cộng kỹ năng cha và con hai lần khi tính tổng.';

COMMENT ON COLUMN "course_skills"."initial_band" IS '4.0..9.0, giảng viên đặt; bước 0.5';

COMMENT ON COLUMN "course_skills"."current_difficulty_rating" IS 'Điểm nội bộ, không phải điểm thi IELTS chính thức';

COMMENT ON COLUMN "course_skills"."weight" IS '0 < weight <= 1';

COMMENT ON TABLE "course_prerequisites" IS 'Khóa học cần hoàn thành trước. Không tự tham chiếu; không tạo chu trình. Điều kiện kỹ năng vẫn được xét riêng.';

COMMENT ON TABLE "chapters" IS 'Tương ứng Unit trong ERD ban đầu.';

COMMENT ON COLUMN "chapters"."position" IS 'Số nguyên dương';

COMMENT ON TABLE "lessons" IS 'Một lesson có một video và nhiều material/exercise. Bản nháp có thể chưa có video; trước publish phải có đúng một video. Thứ tự toàn khóa = chapters.position rồi lessons.position. required_watch_percentage là cấu hình; tiến độ thực tế thuộc enrollment. Không sửa threshold/required/order đã có người học mà không có quy trình chuyển dữ liệu.';

COMMENT ON COLUMN "lessons"."position" IS 'Số nguyên dương';

COMMENT ON COLUMN "lessons"."required_watch_percentage" IS '0 < giá trị <= 100; ngưỡng xem video do instructor đặt. Đây là %completion trong ERD cũ.';

COMMENT ON COLUMN "lessons"."status" IS 'draft / published / hidden / archived';

COMMENT ON TABLE "videos" IS 'Video riêng, không nằm trong lesson_materials. Lesson-Video 1:1 về số lượng tối đa; kiểm tra publish bảo đảm mỗi lesson published có đúng một video. Không thay video hoặc duration khi đã có progress; tạo bản mới hoặc chuyển dữ liệu có kiểm soát.';

COMMENT ON COLUMN "videos"."lesson_id" IS 'UNIQUE bảo đảm tối đa một video mỗi lesson';

COMMENT ON COLUMN "videos"."video_url" IS 'Object key hoặc URL ổn định; không lưu signed URL tạm thời';

COMMENT ON COLUMN "videos"."duration_seconds" IS '>0';

COMMENT ON TABLE "lesson_materials" IS 'Lesson 1:N Material. text cần text_content; audio/slides/file cần resource_url. Video và ngưỡng video không đặt ở bảng này. Học liệu bắt buộc phải được hoàn thành theo chính sách đánh dấu/xác nhận của hệ thống.';

COMMENT ON COLUMN "lesson_materials"."material_type" IS 'text / audio / slides / file; video dùng bảng videos riêng';

COMMENT ON COLUMN "lesson_materials"."resource_url" IS 'URL hoặc object key của học liệu không phải text';

COMMENT ON COLUMN "lesson_materials"."text_content" IS 'Nội dung khi material_type=text';

COMMENT ON COLUMN "lesson_materials"."duration_seconds" IS 'Có thể có với audio; nếu có phải >0';

COMMENT ON COLUMN "lesson_materials"."position" IS '>0';

COMMENT ON TABLE "lesson_skills" IS 'Bài học dạy kỹ năng nào và cần mức đầu vào nào.';

COMMENT ON COLUMN "lesson_skills"."minimum_mastery" IS '0..1, điều kiện bắt đầu';

COMMENT ON COLUMN "lesson_skills"."expected_mastery" IS '0..1, mục tiêu sau bài';

COMMENT ON TABLE "enrollments" IS 'Quan hệ Learner–Course; trạng thái tham gia và tiếp tục học. Resume lesson phải thuộc course. Re-enrol kích hoạt lại bản ghi cũ, giữ tiến độ; thay đổi ghi audit. completed_at có khi status=completed.';

COMMENT ON COLUMN "enrollments"."status" IS 'active / withdrawn / completed';

COMMENT ON TABLE "lesson_progress" IS 'Tiến độ của một người trong một bài. Lesson phải thuộc course của enrollment. completed cần video đạt ngưỡng, toàn bộ material required hoàn thành và toàn bộ exercise required có kết quả đạt. Không chỉ dựa vào nút frontend; bài nộp chờ chấm chưa đạt điều kiện.';

COMMENT ON COLUMN "lesson_progress"."status" IS 'in_progress / completed';

COMMENT ON TABLE "material_progress" IS 'Tiến độ riêng cho material không phải video. Material phải thuộc course của enrollment. Text/slides/file được đánh dấu hoàn thành theo rule nhóm; audio position nếu có nằm trong duration.';

COMMENT ON COLUMN "material_progress"."last_position_seconds" IS 'Dành cho audio nếu có; video resume dùng video_progress';

COMMENT ON TABLE "video_progress" IS 'Mỗi người có trạng thái xem riêng đối với video. Video thuộc course của enrollment. watched_seconds và watched_percentage tính từ hợp video_watch_segments; không lưu thêm phần trăm độc lập dễ mất đồng bộ.';

COMMENT ON COLUMN "video_progress"."last_position_seconds" IS '>=0 và <=duration; chỉ là vị trí resume, không phải thời lượng đã xem';

COMMENT ON COLUMN "video_progress"."completed_at" IS 'Cache khi đã đạt ngưỡng required_watch_percentage của lesson';

COMMENT ON TABLE "video_watch_segments" IS '0 <= start < end <= videos.duration_seconds; video thuộc course của enrollment. Tính độ dài hợp các đoạn, không cộng trùng. Server xác thực heartbeat để tua đến cuối không tự đạt ngưỡng. Đây là bằng chứng phát video tương đối, không chứng minh người học chú ý.';

COMMENT ON TABLE "assessments" IS 'Tương ứng Exercise trong ERD. Lesson 1:N Exercise; dùng chung cho đầu vào, quiz, cuối khóa, kiểm tra tuần và bài nộp. Lesson nếu có phải thuộc course; lesson_quiz và assignment cần lesson; course_final cần course. Khi lesson_id có giá trị, course_id cũng phải có và cùng khóa. Weekly cần assigned_learner_id và week_start; unique có điều kiện trên cặp này khi purpose=weekly. Ít nhất một trong time_limit_seconds/due_at; số lượng và thời lượng >0. File có question_count=NULL. Đóng băng cấu hình đã có attempt hoặc tạo assessment mới.';

COMMENT ON COLUMN "assessments"."course_id" IS 'NULL cho placement/weekly nền tảng';

COMMENT ON COLUMN "assessments"."lesson_id" IS 'Có khi quiz hoặc assignment của bài';

COMMENT ON COLUMN "assessments"."assigned_learner_id" IS 'Bài weekly cá nhân';

COMMENT ON COLUMN "assessments"."purpose" IS 'placement / lesson_quiz / course_final / weekly / assignment';

COMMENT ON COLUMN "assessments"."response_mode" IS 'quiz / file / mixed';

COMMENT ON COLUMN "assessments"."status" IS 'draft / published / closed';

COMMENT ON COLUMN "assessments"."question_count" IS 'Số câu lấy từ pool khi tạo attempt';

COMMENT ON COLUMN "assessments"."time_limit_seconds" IS 'NULL nếu không giới hạn thời lượng';

COMMENT ON COLUMN "assessments"."max_attempts" IS 'NULL nghĩa là không giới hạn';

COMMENT ON COLUMN "assessments"."passing_percent" IS '0..100';

COMMENT ON COLUMN "assessments"."week_start" IS 'Dành cho weekly cá nhân';

COMMENT ON COLUMN "assessments"."grading_rubric" IS 'Tiêu chí chấm Writing/Speaking hoặc bài nộp';

COMMENT ON TABLE "question_banks" IS 'Ngân hàng có metadata và owner; QuestionBank 1:N Question. Quyền sử dụng theo owner/admin; khi course_id có giá trị, bank thuộc khóa đó. Chỉ archive ngân hàng có lịch sử đề thi, không xóa dây chuyền questions/snapshots.';

COMMENT ON COLUMN "question_banks"."course_id" IS 'NULL cho ngân hàng placement/weekly toàn nền tảng';

COMMENT ON COLUMN "question_banks"."status" IS 'active / archived';

COMMENT ON TABLE "questions" IS 'Câu hỏi thuộc question_banks; một kỹ năng chính cho mỗi câu ở MVP. Essay do người chấm; câu hỏi chỉ được dùng khi có quyền với question bank; backend kiểm tra owner/admin và quyền creator. Không tự động chấm Writing/Speaking bằng trắc nghiệm.';

COMMENT ON COLUMN "questions"."question_bank_id" IS 'Mỗi question thuộc một ngân hàng';

COMMENT ON COLUMN "questions"."source_lesson_id" IS 'Để tạo weekly từ bài đã được miễn';

COMMENT ON COLUMN "questions"."question_type" IS 'single_choice / multiple_choice / short_answer / essay';

COMMENT ON COLUMN "questions"."media_url" IS 'Audio/hình/tài liệu dùng kèm câu hỏi';

COMMENT ON COLUMN "questions"."answer_key" IS 'Đáp án text và quy tắc chuẩn hóa; chỉ backend được đọc';

COMMENT ON COLUMN "questions"."status" IS 'draft / active / retired';

COMMENT ON TABLE "question_options" IS 'Các đáp án lựa chọn, tách khỏi câu hỏi. single_choice đúng một option đúng; multiple_choice ít nhất một option đúng; không trả is_correct trong API làm bài.';

COMMENT ON TABLE "assessment_questions" IS 'Pool câu hỏi được phép rút cho một bài đánh giá. question_count >= số câu required và <= tổng pool hợp lệ. Weekly tạo pool theo source_lesson_id của lesson_exemptions còn hiệu lực.';

COMMENT ON COLUMN "assessment_questions"."max_points" IS '>0';

COMMENT ON COLUMN "assessment_questions"."is_required" IS 'Luôn xuất hiện, các câu khác được rút ngẫu nhiên';

COMMENT ON TABLE "assessment_attempts" IS 'Mỗi lần thi hoặc mỗi lần nộp bài là một bản ghi riêng. Nếu có enrollment: learner và course phải khớp assessment. Chỉ 1 attempt in_progress mỗi learner/assessment; khóa transaction khi cấp attempt_number, kiểm tra max_attempts. 0<=score<=max_points; không nhận answer sau expires_at. assigned_learner phải khớp người thi.';

COMMENT ON COLUMN "assessment_attempts"."enrollment_id" IS 'NULL với placement/weekly toàn nền tảng';

COMMENT ON COLUMN "assessment_attempts"."status" IS 'in_progress / submitted / awaiting_grading / graded / cancelled';

COMMENT ON COLUMN "assessment_attempts"."expires_at" IS 'Server chốt từ thời lượng và deadline';

COMMENT ON COLUMN "assessment_attempts"."submission_reason" IS 'manual / timeout';

COMMENT ON COLUMN "assessment_attempts"."max_points" IS '>0, đóng băng cho attempt';

COMMENT ON COLUMN "assessment_attempts"."score" IS 'NULL trước khi chấm đủ';

COMMENT ON COLUMN "assessment_attempts"."is_passed" IS 'NULL trước khi có kết quả cuối';

COMMENT ON COLUMN "assessment_attempts"."graded_by" IS 'NULL khi auto-grade';

COMMENT ON TABLE "attempt_questions" IS 'Đề thực tế và thứ tự câu hỏi/đáp án đã rút ở mỗi lần thi. Câu phải thuộc assessment_questions tương ứng; snapshots bất biến sau khi bắt đầu. Không sinh lại đề khi reload/timeout.';

COMMENT ON COLUMN "attempt_questions"."skill_id" IS 'Snapshot kỹ năng của câu tại thời điểm thi';

COMMENT ON COLUMN "attempt_questions"."question_snapshot" IS 'Prompt, type, media, options kèm thứ tự đã random';

COMMENT ON COLUMN "attempt_questions"."answer_key_snapshot" IS 'Chỉ backend; không nằm trong response làm bài';

COMMENT ON COLUMN "attempt_questions"."max_points" IS '>0';

COMMENT ON TABLE "attempt_answers" IS 'Câu trả lời được autosave và điểm từng câu. Option phải tồn tại trong snapshot của chính câu đó; 0<=awarded_points<=attempt_questions.max_points. Sau khi submitted, chỉ quy trình chấm được cập nhật điểm.';

COMMENT ON COLUMN "attempt_answers"."answer_payload" IS 'Option IDs trong snapshot hoặc nội dung text';

COMMENT ON COLUMN "attempt_answers"."awarded_points" IS 'NULL nếu chưa chấm';

COMMENT ON TABLE "submission_files" IS 'Tệp nộp bài, hỗ trợ file viết và audio/video nói. Chỉ chủ attempt được nộp trước expires_at; giới hạn loại/kích thước file và quyền tải xuống.';

COMMENT ON COLUMN "submission_files"."object_key" IS 'Tệp trong object storage, không nhét binary vào DB';

COMMENT ON TABLE "lesson_exemptions" IS 'Bài được miễn bởi thuật toán, khác với đã học xong. Một exemption còn hiệu lực cho mỗi enrollment/lesson; lesson thuộc course, basis attempt thuộc cùng learner và đã graded. Miễn bài không ghi lesson_progress.completed.';

COMMENT ON COLUMN "lesson_exemptions"."revoked_at" IS 'Có thể thu hồi khi weekly phát hiện thiếu kiến thức';

COMMENT ON TABLE "learner_skill_states" IS 'Trạng thái hiện tại theo từng kỹ năng; cache để gợi ý nhanh. Không có state trước khi đủ dữ liệu thì hiển thị chưa đánh giá. Mapping rating→band/mastery phải có phiên bản, không coi là IELTS chính thức.';

COMMENT ON COLUMN "learner_skill_states"."ability_rating" IS 'Elo nội bộ';

COMMENT ON COLUMN "learner_skill_states"."estimated_band" IS '4.0..9.0 theo phạm vi proposal; có thể NULL khi chưa đủ bằng chứng';

COMMENT ON COLUMN "learner_skill_states"."mastery_score" IS '0..1, không tự đồng nhất với estimated_band';

COMMENT ON COLUMN "learner_skill_states"."target_band" IS 'Mục tiêu theo kỹ năng gốc';

COMMENT ON COLUMN "learner_skill_states"."uncertainty" IS 'Độ bất định nếu thuật toán có hỗ trợ';

COMMENT ON TABLE "learner_rating_events" IS 'Lịch sử thay đổi trình độ để vẽ trajectory và giải thích. source attempt cùng learner, đã graded. Cập nhật event và learner_skill_states trong một transaction; unique chống worker xử lý lặp. MVP chỉ placement/course_final/weekly là bằng chứng cập nhật rating, retake quiz không farm Elo.';

COMMENT ON COLUMN "learner_rating_events"."rating_before" IS 'NULL khi khởi tạo';

COMMENT ON COLUMN "learner_rating_events"."calculation_inputs" IS 'Lưu score, expected, K, difficulty tại thời điểm cập nhật';

COMMENT ON TABLE "course_reviews" IS 'Nhận xét và cảm nhận độ khó, tách khỏi ability rating. Chỉ learner đã completed được review; star_rating không dùng trực tiếp như IELTS band. MVP review chung cho course; cập nhật các skill theo weight bằng rule có phiên bản.';

COMMENT ON COLUMN "course_reviews"."star_rating" IS '1..5: chất lượng trải nghiệm';

COMMENT ON COLUMN "course_reviews"."perceived_difficulty" IS 'too_easy / appropriate / too_hard';

COMMENT ON COLUMN "course_reviews"."status" IS 'visible / hidden';

COMMENT ON TABLE "course_rating_events" IS 'Lịch sử điều chỉnh độ khó khóa học từ kết quả hoặc review. Đúng một nguồn attempt hoặc review; nguồn thuộc course; cặp course/skill tồn tại ở course_skills. Unique (source_attempt_id,skill_id) và (source_review_id,skill_id) khi khác NULL. Cập nhật event+course_skills atomically; review mỗi enrollment tác động tối đa một lần trong MVP.';

COMMENT ON TABLE "recommendations" IS 'Lưu gợi ý cùng lý do và đầu vào, phục vụ kiểm chứng thay đổi learning path. Mỗi batch chỉ thuộc một learner; recommend course published, phù hợp prerequisites; có thể suy ra chọn học qua enrollments. Baseline và adaptive phân biệt bằng algorithm_version.';

COMMENT ON COLUMN "recommendations"."batch_id" IS 'Nhóm các gợi ý trong cùng một lần chạy';

COMMENT ON COLUMN "recommendations"."input_snapshot" IS 'Learner ratings, course difficulty, prerequisites lúc gợi ý';

COMMENT ON TABLE "discussions" IS 'Q&A theo bài học, có trả lời theo thread. Reply phải cùng lesson; parent không có chu trình, MVP giới hạn một cấp reply. Learner chỉ truy cập thảo luận khóa mình đăng ký.';

COMMENT ON COLUMN "discussions"."is_resolved" IS 'Áp dụng cho bài gốc';

COMMENT ON COLUMN "discussions"."status" IS 'visible / hidden / deleted';

COMMENT ON TABLE "notifications" IS 'Thông báo cá nhân về nội dung, deadline, kết quả và kiểm duyệt.';

COMMENT ON COLUMN "notifications"."notification_type" IS 'new_content / deadline / result / moderation / weekly_test';

COMMENT ON COLUMN "notifications"."dedupe_key" IS 'Khóa sự kiện để worker retry không gửi trùng';

COMMENT ON TABLE "content_reports" IS 'Báo cáo nội dung vi phạm, có FK thật đến đối tượng. Chính xác một trong course_id/lesson_id/discussion_id/review_id khác NULL. Admin xử lý và ghi audit; có thể report lesson để chỉ ra học liệu vi phạm.';

COMMENT ON COLUMN "content_reports"."status" IS 'pending / reviewing / resolved / dismissed';

COMMENT ON TABLE "audit_logs" IS 'Lịch sử thao tác nhạy cảm của admin và hệ thống. Append-only; tài khoản ứng dụng không được sửa/xóa log. entity_id là snapshot để log còn tồn tại khi đối tượng bị archive.';

COMMENT ON COLUMN "audit_logs"."actor_id" IS 'NULL khi tác vụ hệ thống';

COMMENT ON COLUMN "audit_logs"."action" IS 'approve_instructor / suspend_user / hide_course ...';

COMMENT ON COLUMN "audit_logs"."entity_id" IS 'Snapshot định danh, cố ý không dùng FK polymorphic';

COMMENT ON COLUMN "audit_logs"."before_data" IS 'Loại bỏ password_hash, token và dữ liệu nhạy cảm';

ALTER TABLE "role_applications" ADD FOREIGN KEY ("applicant_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_applications" ADD FOREIGN KEY ("reviewed_by") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auth_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skills" ADD FOREIGN KEY ("parent_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_prerequisites" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_prerequisites" ADD FOREIGN KEY ("prerequisite_skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "courses" ADD FOREIGN KEY ("instructor_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_skills" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_prerequisites" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_prerequisites" ADD FOREIGN KEY ("prerequisite_course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chapters" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "videos" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_materials" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_skills" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("resume_lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_progress" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "material_progress" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "material_progress" ADD FOREIGN KEY ("material_id") REFERENCES "lesson_materials" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "video_progress" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "video_progress" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "video_watch_segments" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "video_watch_segments" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessments" ADD FOREIGN KEY ("creator_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessments" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessments" ADD FOREIGN KEY ("assigned_learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "question_banks" ADD FOREIGN KEY ("owner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "question_banks" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "questions" ADD FOREIGN KEY ("question_bank_id") REFERENCES "question_banks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "questions" ADD FOREIGN KEY ("creator_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "questions" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "questions" ADD FOREIGN KEY ("source_lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "question_options" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_questions" ADD FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_attempts" ADD FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_attempts" ADD FOREIGN KEY ("learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_attempts" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assessment_attempts" ADD FOREIGN KEY ("graded_by") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attempt_questions" ADD FOREIGN KEY ("attempt_id") REFERENCES "assessment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attempt_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attempt_questions" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attempt_answers" ADD FOREIGN KEY ("attempt_question_id") REFERENCES "attempt_questions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attempt_answers" ADD FOREIGN KEY ("graded_by") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_files" ADD FOREIGN KEY ("attempt_id") REFERENCES "assessment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_exemptions" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_exemptions" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_exemptions" ADD FOREIGN KEY ("basis_attempt_id") REFERENCES "assessment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learner_skill_states" ADD FOREIGN KEY ("learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learner_skill_states" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learner_rating_events" ADD FOREIGN KEY ("learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learner_rating_events" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "learner_rating_events" ADD FOREIGN KEY ("source_attempt_id") REFERENCES "assessment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_reviews" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_rating_events" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_rating_events" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_rating_events" ADD FOREIGN KEY ("source_attempt_id") REFERENCES "assessment_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "course_rating_events" ADD FOREIGN KEY ("source_review_id") REFERENCES "course_reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recommendations" ADD FOREIGN KEY ("learner_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recommendations" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("author_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "discussions" ADD FOREIGN KEY ("parent_id") REFERENCES "discussions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("reporter_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("discussion_id") REFERENCES "discussions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("review_id") REFERENCES "course_reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_reports" ADD FOREIGN KEY ("reviewed_by") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
